/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer-dashboard'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NgoDashboardRouteImport } from './routes/ngo-dashboard'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonorDashboardRouteImport } from './routes/donor-dashboard'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer-dashboard',
  path: '/volunteer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDashboardRoute = NgoDashboardRouteImport.update({
  id: '/ngo-dashboard',
  path: '/ngo-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor-dashboard',
  path: '/donor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/ngo': typeof NgoRoute
  '/ngo-dashboard': typeof NgoDashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/ngo': typeof NgoRoute
  '/ngo-dashboard': typeof NgoDashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donor-dashboard': typeof DonorDashboardRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/ngo': typeof NgoRoute
  '/ngo-dashboard': typeof NgoDashboardRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/browse'
    | '/contact'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/map'
    | '/ngo'
    | '/ngo-dashboard'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tracking'
    | '/volunteer-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/browse'
    | '/contact'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/map'
    | '/ngo'
    | '/ngo-dashboard'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tracking'
    | '/volunteer-dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/browse'
    | '/contact'
    | '/donate'
    | '/donor-dashboard'
    | '/login'
    | '/map'
    | '/ngo'
    | '/ngo-dashboard'
    | '/pricing'
    | '/settings'
    | '/signup'
    | '/tracking'
    | '/volunteer-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NgoRoute: typeof NgoRoute
  NgoDashboardRoute: typeof NgoDashboardRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TrackingRoute: typeof TrackingRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer-dashboard': {
      id: '/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo-dashboard': {
      id: '/ngo-dashboard'
      path: '/ngo-dashboard'
      fullPath: '/ngo-dashboard'
      preLoaderRoute: typeof NgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor-dashboard': {
      id: '/donor-dashboard'
      path: '/donor-dashboard'
      fullPath: '/donor-dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NgoRoute: NgoRoute,
  NgoDashboardRoute: NgoDashboardRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TrackingRoute: TrackingRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
